---
services:

  postgres-db:
    image: postgres:alpine
    restart: unless-stopped
    command: -p 5433
    expose:
      - 5433
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  medilynk-server:
    image: dgclasher/medilynk-server:latest
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - postgres-db
    env_file:
      - .env
    ports:
      - 3000:4000
    